"use client";

import { useMemo, useState } from "react";
type Mode = "cat" | "dog";

const content = {
  cat: { label:"猫", mark:"ね", eyebrow:"A QUIET PLACE WITH CATS", headline:"猫に会いにいこう。", lead:"ひとりの時間に、あたたかな気配を。", sub:"公式情報と公開レビューを確認して選んだ、実在する猫カフェをご案内します。", hero:"https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?auto=format&fit=crop&w=1600&q=90", note:"言葉のいらない午後", place:"猫と過ごす、ひとり時間", placeType:"猫カフェ", guideImage:"https://images.unsplash.com/photo-1543852786-1cf6624b9987?auto=format&fit=crop&w=1400&q=90", quote:"猫に選ばれる人は、待つのが上手。", guide:"猫に好かれようとしなくて大丈夫。同じ部屋で、それぞれの時間を過ごす。その距離がいちばん自然です。", quiz:"静かな観察席", quizText:"猫を追わず、写真や読書と一緒にゆっくり過ごせるお店がおすすめです。", tips:[["香りは控えめに","香水や強い柔軟剤を避けると、猫も安心。"],["フラッシュは使わない","静音モードと明るいレンズが味方です。"],["追わずに、待つ","近くに来てくれた時間を楽しみましょう。"]], shops:[
    ["猫カフェMOCHA 原宿店","東京","平日10分330円〜","10:00〜21:00","原宿駅目の前。明るく整った空間で、仕事・読書にも利用できます。","https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=1200&q=85","東京都渋谷区神宮前1-14-25 4F","清潔でおしゃれ、眺めが良いという声が多い一方、混雑時や猫との距離感には時間帯差があるとの声も。","https://catmocha.jp/shop/harajuku/","https://www.jalan.net/kankou/spt_guide000000193561/kuchikomi/"],
    ["ネコリパブリック東京池袋店","東京","料金は公式で要確認","11:00〜22:00・木休","池袋駅西口から徒歩約5分。保護猫との出会いが支援につながる落ち着いた店。","https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=1200&q=85","東京都豊島区西池袋3丁目","猫を思いやるスタッフの対応や、保護猫がのびのび過ごす様子を評価する声が見られます。","https://www.neco-republic.jp/shop/shop-necorepublic-ikebukuro/","https://map.yahoo.co.jp/v3/place/ZO2818RdLRs"],
    ["Cat Cafe Miysis","神奈川","50分1,700円・1ドリンク付","13:00〜19:00","関内駅徒歩5分。2009年開業、里親募集も行う横浜の保護猫カフェ。","https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=1200&q=85","横浜市中区長者町6-99 2F","猫が膝でくつろいだという体験談もあり、長めの時間設定と保護猫との自然な交流が特徴。","https://www.cat-miysis.com/","https://www.cat-miysis.com/menu"],
    ["猫カフェMOCHA 梅田店","大阪","平日30分1,000円〜","10:00〜20:00","東梅田駅徒歩2分。ワークスペースもあり、一人での長居にも向く明るい店内。","https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=1200&q=85","大阪府大阪市北区小松原町1-7 ミスターりんビル2F","広く清潔な店内でゆっくり過ごせる、スタッフの接客が丁寧という声が多くあります。","https://catmocha.jp/shop/osakaumeda/","https://www.asoview.com/base/163853/asorepo/list/"],
    ["猫カフェMOCHA 京都河原町店","京都","平日30分1,091円〜","11:00〜21:00","京都市役所前駅・三条駅から徒歩5分。1日2回の「ごはんタイム」が名物の広めの店内。","https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=1200&q=85","京都府京都市中京区河原町通三条下る大黒町58 mina 4F","清潔感がある、猫の毛づくろいが行き届いている、スタッフの英語対応も可との声が多くあります。","https://catmocha.jp/shop/kawaramachi/","https://map.yahoo.co.jp/v3/place/F9TCv4Ko32o/review"],
    ["猫カフェMOCHA 名古屋栄店","愛知","平日30分1,000円〜","10:00〜20:00","矢場町駅徒歩1分。中央のキャットタワー型シンボルツリーが目印。","https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=1200&q=85","愛知県名古屋市中区栄3-32-6 BECOME SAKAE 2F","猫の可愛い寝顔に癒される、2時間以上の滞在なら最大料金でお得という声があります。","https://catmocha.jp/shop/nagoya/","https://tabelog.com/aichi/A2301/A230103/23095244/"],
    ["猫カフェMOCHA 天神大名店","福岡","平日30分1,045円〜","10:00〜20:00","天神西通りすぐ。2024年4月開業、漫画1,500冊など長居向けの設備が充実。","https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=1200&q=85","福岡県福岡市中央区大名1-12-6 NEO大名ビル3F","Yahoo!マップ評価5.0。かわいい猫がいっぱいで癒された、おやつをあげると寄ってくるとの声。","https://catmocha.jp/shop/tenjindaimyo/","https://www.jalan.net/kankou/spt_guide000000228913/"],
    ["キャットラウンジ nonnon 仙台中央店","宮城","平日10分200円〜","11:00〜19:00","仙台駅徒歩3分。約30匹の猫が在籍し、Wi-Fi・電源完備で一人利用や作業にも向く空間。","https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=1200&q=85","仙台市青葉区中央1-7-11 トモエヤビル2F","猫たちがリラックスしていて可愛い、清潔感があり安心との声があります。","https://catnonnon.jp/shop/1/","https://miyagiinfo.com/play/animal-cafe/28/"],
    ["猫カフェMOCHA 三宮店","兵庫","平日30分1,000円〜","10:00〜20:00","阪急神戸三宮駅西口から徒歩3分。ナチュラルな内装で1日2回のごはんタイムが見られる。","https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=1200&q=85","兵庫県神戸市中央区下山手通2丁目1-14 アークコースト5F","猫の可愛い姿を写真に収めやすい、マンガ・雑誌読み放題でゆっくりできるとの声。","https://catmocha.jp/shop/kobesannomiya/","https://epark.jp/shopinfo/odk615440/"],
    ["保護猫カフェ ネコリパブリック広島店","広島","平日30分1,100円〜","平日13:00〜20:00・土日祝11:00〜19:00","鷹野橋駅徒歩3分。西日本唯一のネコリパブリック店舗で、保護猫の里親探しを支援する仕組み。","https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=1200&q=85","広島市中区大手町5-5-10 栗原ビル2F","店内が清潔で猫の健康管理がしっかりしている、スタッフが親切との声がある一方、譲渡条件は事前確認をおすすめします。","https://www.neco-republic.jp/shop/shop-necorepublic-hiroshima/","https://loco.yahoo.co.jp/place/g-IAJg47tMwhk/"]]},
  dog: { label:"犬", mark:"い", eyebrow:"A HAPPY PLACE WITH DOGS", headline:"犬に会いにいこう。", lead:"まっすぐなまなざしと、弾む足音。", sub:"公式情報と公開レビューを確認して選んだ、実在する犬カフェをご案内します。", hero:"https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1600&q=90", note:"笑顔がほどける午後", place:"犬と過ごす、ひとり時間", placeType:"犬カフェ", guideImage:"https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1400&q=90", quote:"犬がくれるのは、まっすぐな『大好き』。", guide:"元気な子も、少し人見知りな子もいます。目線を合わせ、名前を呼び、ゆっくり仲良くなりましょう。", quiz:"ゆったりふれあい席", quizText:"スタッフが相性を見ながら紹介してくれる、少人数制のお店がおすすめです。", tips:[["まず手の匂いから","手を低く差し出し、犬から近づくのを待ちます。"],["抱っこはスタッフに確認","犬の体調と気持ちをいちばんに考えます。"],["動きやすい服で","毛や足あとも楽しい思い出になる装いを。"]], shops:[
    ["いぬカフェRio 下北沢店","東京","平日10分250円〜","11:00〜20:00","下北沢駅徒歩3分。低い位置に座り、犬から膝に来るのを待つスタイル。","https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=1200&q=85","東京都世田谷区北沢2-15-16 3F","犬が元気でかわいいという声に加え、おやつの有無や混雑で距離感が変わるとの意見もあります。","https://rio-corp.jp/shops/shimokitazawa/","https://rio-corp.jp/shops/shimokitazawa/"],
    ["いぬカフェRio 鎌倉小町通り店","神奈川","平日10分250円〜","10:00〜19:00","鎌倉駅東口徒歩2分。観光の途中にも立ち寄りやすい犬とのふれあい空間。","https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1200&q=85","鎌倉市小町2-10-1 1F","スタッフが常に見守る安心感、清潔さ、元気な犬を評価する声がある一方、混雑やおやつ時の集中を指摘する声も。","https://rio-corp.jp/shops/kamakura/","https://www.asoview.com/base/162641/asorepo/list/"],
    ["犬カフェらいち","神奈川","50分2,200円・1ドリンク付","10:00〜20:00","本厚木エリア。ふれあいのほか散歩・トリマー・トレーナー体験も用意。","https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=1200&q=85","神奈川県厚木市","公開レビューでは4.8（8件）。人懐っこさ、清潔感、スタッフの親切さを評価する声が多く、料金への意見も。","https://dogcafe-raichi.jp/service/","https://www.jalan.net/kankou/spt_guide000000229906/kuchikomi/"],
    ["いぬカフェRio 茶屋町店","大阪","平日10分250円〜","11:00〜20:00","阪急大阪梅田駅徒歩5分。小〜中型犬16頭が在籍し、低い姿勢で座って犬から寄ってくるのを待つスタイル。","https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=1200&q=85","大阪府大阪市北区茶屋町4-13","2025年7月開業のため個別口コミは少なめですが、同チェーン他店同様に人懐っこい犬とスタッフ対応の良さが評価されています。","https://rio-corp.jp/shops/%e8%8c%b6%e5%b1%8b%e7%94%ba%e5%ba%97/","https://www.asoview.com/leisure/act1556/location/prf270000/"],
    ["いぬカフェRio 京都店","京都","平日10分250円〜","11:00〜20:00","京都河原町駅徒歩7分。17頭の犬と触れ合え、低い位置に座って自然に寄ってくるのを待つスタイル。","https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1200&q=85","京都府京都市中京区新京極通三条下る桜之町398 SMJ三条共同ビル2F","口コミ500件超。犬種が多くおやつを持つとボスになった気分、一人暮らしで犬を飼えない身にはパラダイスとの声。","https://rio-corp.jp/shops/kyoto/","https://www.tripadvisor.jp/ShowUserReviews-g298564-d27167119-r968102406-Puppy_Cafe_Rio_Kyoto-Kyoto_Kyoto_Prefecture_Kinki.html"],
    ["いぬカフェRio 常滑店","愛知","平日10分220円〜","10:00〜20:00","りんくう常滑駅徒歩5分、イオンモール常滑内。犬20頭・猫14頭が同居する複合型で、家族連れにも一人利用にも対応。","https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=1200&q=85","愛知県常滑市りんくう町2丁目20番3 イオンモール常滑1F","スタッフが親切、犬も猫も人懐っこい、年齢制限がなく安心との声があります。","https://rio-corp.jp/shops/tokoname/","https://www.asoview.com/base/162660/asorepo/list/"],
    ["いぬカフェRio 福岡店","福岡","平日10分220円〜","10:00〜20:00","イオンモール福岡1F。チワワ・ポメラニアン・トイプードルなど20頭が在籍。","https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=1200&q=85","福岡県糟屋郡粕屋町大字酒殿字老ノ木192-1 イオンモール福岡1F","評価4.41（32件）。にぎやかでファミリー向き、対応が良く子供でも楽しめるとの声。","https://rio-corp.jp/shops/fukuoka/","https://www.jalan.net/kankou/spt_guide000000228248/"],
    ["いぬカフェRio 仙台店","宮城","平日10分220円〜","11:00〜20:00","JR仙台駅西口から徒歩8分。予約不要でふらっと立ち寄れる、小〜中型犬中心の落ち着いた店舗。","https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1200&q=85","宮城県仙台市青葉区一番町3-1-24 山一商店ビルB1F","評価4.17。スタッフがフレンドリー、値段がリーズナブルとの声がある一方、清潔面の指摘も一部あります。","https://rio-corp.jp/shops/sendai/","https://map.yahoo.co.jp/v3/place/01glSu-AAuc"],
    ["保護犬ふれあいカフェ GUARDIAN","兵庫","料金は公式で要確認","料金・営業時間は公式で要確認","新開地駅・湊川公園駅から徒歩2〜4分。殺処分対象になりやすい雑種の中型犬などを保護し、里親探しにつなげる保護犬ふれあいカフェ。","https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=1200&q=85","神戸市兵庫区中道通1丁目2-11","施設内が清潔で臭いが気にならない、スタッフが優しく親切、保護犬の里親になりたいと思ったとの声があります。","https://kobeguardian.com/","https://map.yahoo.co.jp/v3/place/iXxXOJlZeow/review"],
    ["いぬカフェRio 広島店","広島","平日10分220円〜","10:00〜20:00","皆実町二丁目駅徒歩5分、ゆめタウン広島内。小型犬20頭が在籍し、低い姿勢で自然な触れ合いを待つスタイル。","https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=1200&q=85","広島県広島市南区皆実町2丁目8-17 ゆめタウン広島1F","かわいいワンちゃんで楽しめた、スタッフ・犬ともにホスピタリティが高いとの声があります。","https://rio-corp.jp/shops/hiroshima/","https://www.asoview.com/base/163286/asorepo/list/"],
    ["犬とふれあえるカフェ（琴似）","北海道","1時間1,800円〜","予約制・木曜定休","地下鉄琴似駅5番出口から徒歩5分。2024年4月開業、小型犬から大型犬まで20頭が在籍する予約制カフェ。公式サイトは予約ページのみのため、来店前に最新情報をご確認ください。","https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1200&q=85","北海道札幌市西区二十四軒4条7丁目5-18 岩井ビル1F","人懐っこい犬が膝に乗ってくる、癒されたとの声があります。","https://frm.rsv-site.owl-solution.jp/inucafe-sapporo","https://www.wanchan-life.jp/column/sapporo-cafe/"]]}
} as const;
const products = [["◌","表情を、やさしく残す","小型ミラーレス入門セット","参考 ¥89,800"],["⌁","毛を気にせず、余韻を持ち帰る","携帯クリーナー＆ケアセット","参考 ¥3,280"],["▤","会えない夜に、記録を一冊に","写真日記フォトブック","参考 ¥2,980〜"]];

export function PetCafePage({mode}:{mode:Mode}){
 const [area,setArea]=useState("すべて"),[quiet,setQuiet]=useState(false),[saved,setSaved]=useState<string[]>([]),[quiz,setQuiz]=useState(false); const c=content[mode];
 const areas=useMemo(()=>["すべて",...Array.from(new Set(c.shops.map(s=>s[1])))],[c]);
 const shops=useMemo(()=>c.shops.filter(s=>area==="すべて"||s[1]===area),[c,area]);
 const toggle=(n:string)=>setSaved(s=>s.includes(n)?s.filter(x=>x!==n):[...s,n]);
 return <main className={`${mode}-mode`}>
  <div className="species-switch" aria-label="猫派ページと犬派ページの切り替え"><span>あなたはどっち派？</span><a className={mode==="cat"?"selected":""} href="/cat-cafe/">🐈 猫派ページ</a><a className={mode==="dog"?"selected":""} href="/dog-cafe/">🐕 犬派ページ</a></div>
  <header className="nav"><a className="brand" href="#top"><span>{c.mark}</span>{c.label}日和</a><nav><a href="#find">{c.placeType}を探す</a><a href="#guide">はじめてガイド</a><a href="#journal">おすすめ用品</a></nav><a className="saved" href="#find">♡ 保存したお店 <b>{saved.length}</b></a></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">{c.eyebrow}</p><h1>今日は、<br/><em>{c.headline}</em></h1><p className="lead">{c.lead}<br/>{c.sub}</p><div className="hero-actions"><a className="button primary" href="#find">近くの{c.placeType}を探す <span>→</span></a><button className="text-button" onClick={()=>setQuiz(true)}>3つの質問で相性診断</button></div><div className="trust"><span>掲載店は編集部が確認</span><span>ひとり客目線でレビュー</span><span>広告も正直に表示</span></div></div><div className="hero-image" style={{backgroundImage:`linear-gradient(90deg,rgba(31,41,37,.08),transparent),url(${c.hero})`}}><div className="photo-label"><small>EDITOR&apos;S NOTE</small><strong>{c.note}</strong><span>{c.place}</span></div></div></section>
  <section className="search-section" id="find"><div className="section-heading"><div><p className="eyebrow">VERIFIED PLACE DATA</p><h2>実際に行ける、{c.label}のいる場所。</h2></div><p>公式情報は2026年7月15日確認。<br/>料金・営業時間は来店前に再確認してください。</p></div><div className="filters"><div>{areas.map(x=><button key={x} className={area===x?"active":""} onClick={()=>setArea(x)}>{x}</button>)}</div><label><input type="checkbox" checked={quiet} onChange={e=>setQuiet(e.target.checked)}/> ゆっくり過ごせる</label></div><div className="cafe-grid">{shops.map((s,i)=><article className="cafe-card" key={s[0]}><div className="card-image" style={{backgroundImage:`url(${s[5]})`}}><span className="rank">0{i+1}</span><button className={saved.includes(s[0])?"heart on":"heart"} onClick={()=>toggle(s[0])} aria-label={`${s[0]}を保存`}>{saved.includes(s[0])?"♥":"♡"}</button></div><div className="card-body"><div className="meta">{s[1]} ・ {s[3]}</div><h3>{s[0]}</h3><p>{s[4]}</p><p className="address">⌖ {s[6]}</p><div className="review-box"><small>口コミ傾向</small><p>{s[7]}</p><a href={s[9]} target="_blank" rel="noopener noreferrer">レビュー出典を見る ↗</a></div><div className="tags"><span>実在店舗</span><span>{quiet?"ゆっくり過ごせる":"公式確認済み"}</span></div><div className="card-foot"><strong>{s[2]}</strong><a href={s[8]} target="_blank" rel="noopener noreferrer">公式サイト ↗</a></div></div></article>)}</div></section>
  <section className="guide" id="guide"><div className="guide-photo" style={{backgroundImage:`linear-gradient(#0000,#16251c88),url(${c.guideImage})`}}><span>{c.quote}</span></div><div className="guide-copy"><p className="eyebrow">FIRST VISIT GUIDE</p><h2>はじめての日も、<br/>心地よく。</h2><p>{c.guide}</p><ol>{c.tips.map((t,i)=><li key={t[0]}><b>0{i+1}</b><span><strong>{t[0]}</strong>{t[1]}</span></li>)}</ol><a className="button ink" href="#journal">おすすめ用品を見る →</a></div></section>
  <section className="shop" id="journal"><div className="section-heading"><div><p className="eyebrow">TAKE THE FEELING HOME</p><h2>余韻を、日常へ。</h2></div><p>来店前後に役立つものだけ。<br/><small>PR：外部リンクはアフィリエイト提携後に計測リンクへ差し替え可能です。</small></p></div><div className="item-grid">{products.map((p,i)=><article className="item" key={p[2]}><div className="item-art">{p[0]}</div><span>PR ・ {c.label}との時間に</span><h3>{p[1]}</h3><p>{p[2]}</p><div><strong>{p[3]}</strong><a className="product-link" href={["https://www.amazon.co.jp/s?k=ミラーレスカメラ+初心者","https://www.amazon.co.jp/s?k=携帯+洋服ブラシ+ペットの毛","https://photobook.kitamura.jp/"][i]} target="_blank" rel="nofollow sponsored noopener">商品を比較 →</a></div></article>)}</div><div className="booking-strip"><div><span>PR / 予約導線</span><h3>混雑する日は、予約できる体験プランから。</h3><p>予約サイトのポイント還元や限定プランを比較できます。</p></div><a href={mode==="dog"?"https://www.jalan.net/kankou/spt_guide000000229906/":"https://www.jalan.net/kankou/spt_guide000000193561/"} target="_blank" rel="nofollow sponsored noopener">体験プランを確認する →</a></div></section>
  <section className="story"><p>犬のまっすぐさも、<br/>猫の静けさも知っている。</p><span>犬との別れを経て、猫カフェに癒されたからこそ。<br/>どちらの魅力にも、同じ敬意を込めて案内します。</span></section>
  <footer><div className="brand"><span>{c.mark}</span>{c.label}日和</div><p>{c.label}と人、どちらにもやさしい時間を。</p><div><a href="#find">お店を探す</a><a href="#guide">運営ポリシー</a><a href="#journal">広告掲載について</a></div><small>© 2026 PET BIYORI. 店舗情報・口コミ傾向は公開情報を編集部が要約。写真はイメージです。</small></footer>
  {quiz&&<div className="modal-backdrop" onClick={()=>setQuiz(false)}><section className="modal" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setQuiz(false)}>×</button><p className="eyebrow">YOUR {mode.toUpperCase()} CAFE TYPE</p><h2>あなたには「{c.quiz}」</h2><p>{c.quizText}</p><button className="button primary" onClick={()=>{setQuiet(true);setQuiz(false);document.querySelector("#find")?.scrollIntoView({behavior:"smooth"})}}>おすすめを見る →</button></section></div>}
 </main>
}

export default function Home(){return <main className="portal"><div className="portal-intro"><p className="eyebrow">PET BIYORI</p><h1>どちらの気配に、<br/>会いにいきますか。</h1><p>犬のまっすぐさも、猫の静けさも知っている。<br/>ひとりの時間に寄り添う場所を、動物別にご案内します。</p></div><div className="portal-choices"><a className="portal-card cat-choice" href="/cat-cafe/"><span>CAT CAFE GUIDE</span><div><small>静かな気配に癒されたい日</small><h2>猫派ページへ</h2><b>→</b></div></a><a className="portal-card dog-choice" href="/dog-cafe/"><span>DOG CAFE GUIDE</span><div><small>まっすぐな笑顔に会いたい日</small><h2>犬派ページへ</h2><b>→</b></div></a></div></main>}
