"use client";

import { useMemo, useState } from "react";
type Mode = "cat" | "dog";

const content = {
  cat: { label:"猫", mark:"ね", eyebrow:"A QUIET PLACE WITH CATS", headline:"猫に会いにいこう。", lead:"ひとりの時間に、あたたかな気配を。", sub:"あなたの過ごし方に合う猫カフェを、丁寧に選びました。", hero:"https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?auto=format&fit=crop&w=1600&q=90", note:"言葉のいらない午後", place:"at 猫灯り 鎌倉", placeType:"猫カフェ", guideImage:"https://images.unsplash.com/photo-1543852786-1cf6624b9987?auto=format&fit=crop&w=1400&q=90", quote:"猫に選ばれる人は、待つのが上手。", guide:"猫に好かれようとしなくて大丈夫。同じ部屋で、それぞれの時間を過ごす。その距離がいちばん自然です。", quiz:"静かな観察席", quizText:"猫を追わず、写真や読書と一緒にゆっくり過ごせるお店がおすすめです。", tips:[["香りは控えめに","香水や強い柔軟剤を避けると、猫も安心。"],["フラッシュは使わない","静音モードと明るいレンズが味方です。"],["追わずに、待つ","近くに来てくれた時間を楽しみましょう。"]], shops:[["ねこの間 代官山","東京","¥1,600〜","保護猫 14匹","読書席と小さな縁側。ひとりで過ごしやすい。","https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=1200&q=85"],["mellow cat 吉祥寺","東京","¥1,400〜","猫 18匹","スタッフの距離感が心地よく、初めてでも安心。","https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=1200&q=85"],["猫灯り 鎌倉","神奈川","¥1,800〜","保護猫 11匹","古民家の光と影。写真をゆっくり撮りたい日に。","https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=1200&q=85"]]},
  dog: { label:"犬", mark:"い", eyebrow:"A HAPPY PLACE WITH DOGS", headline:"犬に会いにいこう。", lead:"まっすぐなまなざしと、弾む足音。", sub:"ひとりでも自然に笑顔になれるドッグカフェを選びました。", hero:"https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1600&q=90", note:"笑顔がほどける午後", place:"at 犬日和 二子玉川", placeType:"ドッグカフェ", guideImage:"https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1400&q=90", quote:"犬がくれるのは、まっすぐな『大好き』。", guide:"元気な子も、少し人見知りな子もいます。目線を合わせ、名前を呼び、ゆっくり仲良くなりましょう。", quiz:"ゆったりふれあい席", quizText:"スタッフが相性を見ながら紹介してくれる、少人数制のお店がおすすめです。", tips:[["まず手の匂いから","手を低く差し出し、犬から近づくのを待ちます。"],["抱っこはスタッフに確認","犬の体調と気持ちをいちばんに考えます。"],["動きやすい服で","毛や足あとも楽しい思い出になる装いを。"]], shops:[["犬日和 二子玉川","東京","¥1,700〜","犬 12匹","穏やかな小型犬中心。初めてのひとり利用にも。","https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=1200&q=85"],["wag & cup 蔵前","東京","¥1,500〜","保護犬 9匹","散歩のような距離感で、ゆっくり仲良くなれる。","https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1200&q=85"],["わんこの庭 横浜","神奈川","¥1,900〜","犬 15匹","小さな室内庭園。犬たちの遊ぶ姿を眺める席も。","https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=1200&q=85"]]}
} as const;
const products = [["◌","表情を、やさしく残す","小型ミラーレス入門セット","参考 ¥89,800"],["⌁","毛を気にせず、余韻を持ち帰る","携帯クリーナー＆ケアセット","参考 ¥3,280"],["▤","会えない夜に、記録を一冊に","写真日記フォトブック","参考 ¥2,980〜"]];

export function PetCafePage({mode}:{mode:Mode}){
 const [area,setArea]=useState("すべて"),[quiet,setQuiet]=useState(false),[saved,setSaved]=useState<string[]>([]),[quiz,setQuiz]=useState(false); const c=content[mode];
 const shops=useMemo(()=>c.shops.filter(s=>area==="すべて"||s[1]===area),[c,area]);
 const toggle=(n:string)=>setSaved(s=>s.includes(n)?s.filter(x=>x!==n):[...s,n]);
 return <main className={`${mode}-mode`}>
  <div className="species-switch" aria-label="猫派ページと犬派ページの切り替え"><span>あなたはどっち派？</span><a className={mode==="cat"?"selected":""} href="/cat-cafe/">🐈 猫派ページ</a><a className={mode==="dog"?"selected":""} href="/dog-cafe/">🐕 犬派ページ</a></div>
  <header className="nav"><a className="brand" href="#top"><span>{c.mark}</span>{c.label}日和</a><nav><a href="#find">{c.placeType}を探す</a><a href="#guide">はじめてガイド</a><a href="#journal">おすすめ用品</a></nav><a className="saved" href="#find">♡ 保存したお店 <b>{saved.length}</b></a></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">{c.eyebrow}</p><h1>今日は、<br/><em>{c.headline}</em></h1><p className="lead">{c.lead}<br/>{c.sub}</p><div className="hero-actions"><a className="button primary" href="#find">近くの{c.placeType}を探す <span>→</span></a><button className="text-button" onClick={()=>setQuiz(true)}>3つの質問で相性診断</button></div><div className="trust"><span>掲載店は編集部が確認</span><span>ひとり客目線でレビュー</span><span>広告も正直に表示</span></div></div><div className="hero-image" style={{backgroundImage:`linear-gradient(90deg,rgba(31,41,37,.08),transparent),url(${c.hero})`}}><div className="photo-label"><small>EDITOR&apos;S NOTE</small><strong>{c.note}</strong><span>{c.place}</span></div></div></section>
  <section className="search-section" id="find"><div className="section-heading"><div><p className="eyebrow">FIND YOUR PLACE</p><h2>あなたに合う、{c.label}のいる場所。</h2></div><p>混雑、過ごし方、{c.label}との距離。<br/>実際に訪れてわかったことを載せています。</p></div><div className="filters"><div>{["すべて","東京","神奈川"].map(x=><button key={x} className={area===x?"active":""} onClick={()=>setArea(x)}>{x}</button>)}</div><label><input type="checkbox" checked={quiet} onChange={e=>setQuiet(e.target.checked)}/> ゆっくり過ごせる</label></div><div className="cafe-grid">{shops.map((s,i)=><article className="cafe-card" key={s[0]}><div className="card-image" style={{backgroundImage:`url(${s[5]})`}}><span className="rank">0{i+1}</span><button className={saved.includes(s[0])?"heart on":"heart"} onClick={()=>toggle(s[0])} aria-label={`${s[0]}を保存`}>{saved.includes(s[0])?"♥":"♡"}</button></div><div className="card-body"><div className="meta">{s[1]} ・ {s[3]}</div><h3>{s[0]}</h3><p>{s[4]}</p><div className="tags"><span>おひとり歓迎</span><span>{quiet?"ゆっくり過ごせる":"初心者向け"}</span></div><div className="card-foot"><strong>{s[2]}</strong><a href="#guide">詳しく見る →</a></div></div></article>)}</div></section>
  <section className="guide" id="guide"><div className="guide-photo" style={{backgroundImage:`linear-gradient(#0000,#16251c88),url(${c.guideImage})`}}><span>{c.quote}</span></div><div className="guide-copy"><p className="eyebrow">FIRST VISIT GUIDE</p><h2>はじめての日も、<br/>心地よく。</h2><p>{c.guide}</p><ol>{c.tips.map((t,i)=><li key={t[0]}><b>0{i+1}</b><span><strong>{t[0]}</strong>{t[1]}</span></li>)}</ol><a className="button ink" href="#journal">おすすめ用品を見る →</a></div></section>
  <section className="shop" id="journal"><div className="section-heading"><div><p className="eyebrow">TAKE THE FEELING HOME</p><h2>余韻を、日常へ。</h2></div><p>本当に役立つものだけ。<br/><small>※商品リンクにはアフィリエイト広告が含まれます。</small></p></div><div className="item-grid">{products.map(p=><article className="item" key={p[2]}><div className="item-art">{p[0]}</div><span>{c.label}との時間に</span><h3>{p[1]}</h3><p>{p[2]}</p><div><strong>{p[3]}</strong><button aria-label={`${p[2]}を見る`}>→</button></div></article>)}</div></section>
  <section className="story"><p>犬のまっすぐさも、<br/>猫の静けさも知っている。</p><span>犬との別れを経て、猫カフェに癒されたからこそ。<br/>どちらの魅力にも、同じ敬意を込めて案内します。</span></section>
  <footer><div className="brand"><span>{c.mark}</span>{c.label}日和</div><p>{c.label}と人、どちらにもやさしい時間を。</p><div><a href="#find">お店を探す</a><a href="#guide">運営ポリシー</a><a href="#journal">広告掲載について</a></div><small>© 2026 PET BIYORI. Photos and venues are demonstrations.</small></footer>
  {quiz&&<div className="modal-backdrop" onClick={()=>setQuiz(false)}><section className="modal" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setQuiz(false)}>×</button><p className="eyebrow">YOUR {mode.toUpperCase()} CAFE TYPE</p><h2>あなたには「{c.quiz}」</h2><p>{c.quizText}</p><button className="button primary" onClick={()=>{setQuiet(true);setQuiz(false);document.querySelector("#find")?.scrollIntoView({behavior:"smooth"})}}>おすすめを見る →</button></section></div>}
 </main>
}

export default function Home(){return <main className="portal"><div className="portal-intro"><p className="eyebrow">PET BIYORI</p><h1>どちらの気配に、<br/>会いにいきますか。</h1><p>犬のまっすぐさも、猫の静けさも知っている。<br/>ひとりの時間に寄り添う場所を、動物別にご案内します。</p></div><div className="portal-choices"><a className="portal-card cat-choice" href="/cat-cafe/"><span>CAT CAFE GUIDE</span><div><small>静かな気配に癒されたい日</small><h2>猫派ページへ</h2><b>→</b></div></a><a className="portal-card dog-choice" href="/dog-cafe/"><span>DOG CAFE GUIDE</span><div><small>まっすぐな笑顔に会いたい日</small><h2>犬派ページへ</h2><b>→</b></div></a></div></main>}
