"use client";

import { useMemo, useState } from "react";
type Mode = "cat" | "dog";

const content = {
  cat: { label:"猫", mark:"ね", eyebrow:"A QUIET PLACE WITH CATS", headline:"猫に会いにいこう。", lead:"ひとりの時間に、あたたかな気配を。", sub:"公式情報と公開レビューを確認して選んだ、実在する猫カフェをご案内します。", hero:"https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?auto=format&fit=crop&w=1600&q=90", note:"言葉のいらない午後", place:"猫と過ごす、ひとり時間", placeType:"猫カフェ", guideImage:"https://images.unsplash.com/photo-1543852786-1cf6624b9987?auto=format&fit=crop&w=1400&q=90", quote:"猫に選ばれる人は、待つのが上手。", guide:"猫に好かれようとしなくて大丈夫。同じ部屋で、それぞれの時間を過ごす。その距離がいちばん自然です。", quiz:"静かな観察席", quizText:"猫を追わず、写真や読書と一緒にゆっくり過ごせるお店がおすすめです。", tips:[["香りは控えめに","香水や強い柔軟剤を避けると、猫も安心。"],["フラッシュは使わない","静音モードと明るいレンズが味方です。"],["追わずに、待つ","近くに来てくれた時間を楽しみましょう。"]], shops:[
    ["猫カフェMOCHA 原宿店","東京","平日10分330円〜","10:00〜21:00","原宿駅目の前。明るく整った空間で、仕事・読書にも利用できます。","https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=1200&q=85","東京都渋谷区神宮前1-14-25 4F","清潔でおしゃれ、眺めが良いという声が多い一方、混雑時や猫との距離感には時間帯差があるとの声も。","https://catmocha.jp/shop/harajuku/","https://www.jalan.net/kankou/spt_guide000000193561/kuchikomi/"],
    ["ネコリパブリック東京池袋店","東京","料金は公式で要確認","11:00〜22:00・木休","池袋駅西口から徒歩約5分。保護猫との出会いが支援につながる落ち着いた店。","https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=1200&q=85","東京都豊島区西池袋3丁目","猫を思いやるスタッフの対応や、保護猫がのびのび過ごす様子を評価する声が見られます。","https://www.neco-republic.jp/shop/shop-necorepublic-ikebukuro/","https://map.yahoo.co.jp/v3/place/ZO2818RdLRs"],
    ["Cat Cafe Miysis","神奈川","50分1,700円・1ドリンク付","13:00〜19:00","関内駅徒歩5分。2009年開業、里親募集も行う横浜の保護猫カフェ。","https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=1200&q=85","横浜市中区長者町6-99 2F","猫が膝でくつろいだという体験談もあり、長めの時間設定と保護猫との自然な交流が特徴。","https://www.cat-miysis.com/","https://www.cat-miysis.com/menu"]]},
  dog: { label:"犬", mark:"い", eyebrow:"A HAPPY PLACE WITH DOGS", headline:"犬に会いにいこう。", lead:"まっすぐなまなざしと、弾む足音。", sub:"公式情報と公開レビューを確認して選んだ、実在する犬カフェをご案内します。", hero:"https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1600&q=90", note:"笑顔がほどける午後", place:"犬と過ごす、ひとり時間", placeType:"犬カフェ", guideImage:"https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1400&q=90", quote:"犬がくれるのは、まっすぐな『大好き』。", guide:"元気な子も、少し人見知りな子もいます。目線を合わせ、名前を呼び、ゆっくり仲良くなりましょう。", quiz:"ゆったりふれあい席", quizText:"スタッフが相性を見ながら紹介してくれる、少人数制のお店がおすすめです。", tips:[["まず手の匂いから","手を低く差し出し、犬から近づくのを待ちます。"],["抱っこはスタッフに確認","犬の体調と気持ちをいちばんに考えます。"],["動きやすい服で","毛や足あとも楽しい思い出になる装いを。"]], shops:[
    ["いぬカフェRio 下北沢店","東京","平日10分250円〜","11:00〜20:00","下北沢駅徒歩3分。低い位置に座り、犬から膝に来るのを待つスタイル。","https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=1200&q=85","東京都世田谷区北沢2-15-16 3F","犬が元気でかわいいという声に加え、おやつの有無や混雑で距離感が変わるとの意見もあります。","https://rio-corp.jp/shops/shimokitazawa/","https://rio-corp.jp/shops/shimokitazawa/"],
    ["いぬカフェRio 鎌倉小町通り店","神奈川","平日10分250円〜","10:00〜19:00","鎌倉駅東口徒歩2分。観光の途中にも立ち寄りやすい犬とのふれあい空間。","https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1200&q=85","鎌倉市小町2-10-1 1F","スタッフが常に見守る安心感、清潔さ、元気な犬を評価する声がある一方、混雑やおやつ時の集中を指摘する声も。","https://rio-corp.jp/shops/kamakura/","https://www.asoview.com/base/162641/asorepo/list/"],
    ["犬カフェらいち","神奈川","50分2,200円・1ドリンク付","10:00〜20:00","本厚木エリア。ふれあいのほか散歩・トリマー・トレーナー体験も用意。","https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=1200&q=85","神奈川県厚木市","公開レビューでは4.8（8件）。人懐っこさ、清潔感、スタッフの親切さを評価する声が多く、料金への意見も。","https://dogcafe-raichi.jp/service/","https://www.jalan.net/kankou/spt_guide000000229906/kuchikomi/"]]}
} as const;
const products = [["◌","表情を、やさしく残す","小型ミラーレス入門セット","参考 ¥89,800"],["⌁","毛を気にせず、余韻を持ち帰る","携帯クリーナー＆ケアセット","参考 ¥3,280"],["▤","会えない夜に、記録を一冊に","写真日記フォトブック","参考 ¥2,980〜"]];

export function PetCafePage({mode}:{mode:Mode}){
 const [area,setArea]=useState("すべて"),[quiet,setQuiet]=useState(false),[saved,setSaved]=useState<string[]>([]),[quiz,setQuiz]=useState(false); const c=content[mode];
 const shops=useMemo(()=>c.shops.filter(s=>area==="すべて"||s[1]===area),[c,area]);
 const toggle=(n:string)=>setSaved(s=>s.includes(n)?s.filter(x=>x!==n):[...s,n]);
 return <main className={`${mode}-mode`}>
  <div className="species-switch" aria-label="猫派ページと犬派ページの切り替え"><span>あなたはどっち派？</span><a className={mode==="cat"?"selected":""} href="/cat-cafe/">🐈 猫派ページ</a><a className={mode==="dog"?"selected":""} href="/dog-cafe/">🐕 犬派ページ</a></div>
  <header className="nav"><a className="brand" href="#top"><span>{c.mark}</span>{c.label}日和</a><nav><a href="#find">{c.placeType}を探す</a><a href="#guide">はじめてガイド</a><a href="#journal">おすすめ用品</a></nav><a className="saved" href="#find">♡ 保存したお店 <b>{saved.length}</b></a></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">{c.eyebrow}</p><h1>今日は、<br/><em>{c.headline}</em></h1><p className="lead">{c.lead}<br/>{c.sub}</p><div className="hero-actions"><a className="button primary" href="#find">近くの{c.placeType}を探す <span>→</span></a><button className="text-button" onClick={()=>setQuiz(true)}>3つの質問で相性診断</button></div><div className="trust"><span>掲載店は編集部が確認</span><span>ひとり客目線でレビュー</span><span>広告も正直に表示</span></div></div><div className="hero-image" style={{backgroundImage:`linear-gradient(90deg,rgba(31,41,37,.08),transparent),url(${c.hero})`}}><div className="photo-label"><small>EDITOR&apos;S NOTE</small><strong>{c.note}</strong><span>{c.place}</span></div></div></section>
  <section className="search-section" id="find"><div className="section-heading"><div><p className="eyebrow">VERIFIED PLACE DATA</p><h2>実際に行ける、{c.label}のいる場所。</h2></div><p>公式情報は2026年7月15日確認。<br/>料金・営業時間は来店前に再確認してください。</p></div><div className="filters"><div>{["すべて","東京","神奈川"].map(x=><button key={x} className={area===x?"active":""} onClick={()=>setArea(x)}>{x}</button>)}</div><label><input type="checkbox" checked={quiet} onChange={e=>setQuiet(e.target.checked)}/> ゆっくり過ごせる</label></div><div className="cafe-grid">{shops.map((s,i)=><article className="cafe-card" key={s[0]}><div className="card-image" style={{backgroundImage:`url(${s[5]})`}}><span className="rank">0{i+1}</span><button className={saved.includes(s[0])?"heart on":"heart"} onClick={()=>toggle(s[0])} aria-label={`${s[0]}を保存`}>{saved.includes(s[0])?"♥":"♡"}</button></div><div className="card-body"><div className="meta">{s[1]} ・ {s[3]}</div><h3>{s[0]}</h3><p>{s[4]}</p><p className="address">⌖ {s[6]}</p><div className="review-box"><small>口コミ傾向</small><p>{s[7]}</p><a href={s[9]} target="_blank" rel="noopener noreferrer">レビュー出典を見る ↗</a></div><div className="tags"><span>実在店舗</span><span>{quiet?"ゆっくり過ごせる":"公式確認済み"}</span></div><div className="card-foot"><strong>{s[2]}</strong><a href={s[8]} target="_blank" rel="noopener noreferrer">公式サイト ↗</a></div></div></article>)}</div></section>
  <section className="guide" id="guide"><div className="guide-photo" style={{backgroundImage:`linear-gradient(#0000,#16251c88),url(${c.guideImage})`}}><span>{c.quote}</span></div><div className="guide-copy"><p className="eyebrow">FIRST VISIT GUIDE</p><h2>はじめての日も、<br/>心地よく。</h2><p>{c.guide}</p><ol>{c.tips.map((t,i)=><li key={t[0]}><b>0{i+1}</b><span><strong>{t[0]}</strong>{t[1]}</span></li>)}</ol><a className="button ink" href="#journal">おすすめ用品を見る →</a></div></section>
  <section className="shop" id="journal"><div className="section-heading"><div><p className="eyebrow">TAKE THE FEELING HOME</p><h2>余韻を、日常へ。</h2></div><p>来店前後に役立つものだけ。<br/><small>PR：外部リンクはアフィリエイト提携後に計測リンクへ差し替え可能です。</small></p></div><div className="item-grid">{products.map((p,i)=><article className="item" key={p[2]}><div className="item-art">{p[0]}</div><span>PR ・ {c.label}との時間に</span><h3>{p[1]}</h3><p>{p[2]}</p><div><strong>{p[3]}</strong><a className="product-link" href={["https://www.amazon.co.jp/s?k=ミラーレスカメラ+初心者","https://www.amazon.co.jp/s?k=携帯+洋服ブラシ+ペットの毛","https://photobook.kitamura.jp/"][i]} target="_blank" rel="nofollow sponsored noopener">商品を比較 →</a></div></article>)}</div><div className="booking-strip"><div><span>PR / 予約導線</span><h3>混雑する日は、予約できる体験プランから。</h3><p>予約サイトのポイント還元や限定プランを比較できます。</p></div><a href={mode==="dog"?"https://www.jalan.net/kankou/spt_guide000000229906/":"https://www.jalan.net/kankou/spt_guide000000193561/"} target="_blank" rel="nofollow sponsored noopener">体験プランを確認する →</a></div></section>
  <section className="story"><p>犬のまっすぐさも、<br/>猫の静けさも知っている。</p><span>犬との別れを経て、猫カフェに癒されたからこそ。<br/>どちらの魅力にも、同じ敬意を込めて案内します。</span></section>
  <footer><div className="brand"><span>{c.mark}</span>{c.label}日和</div><p>{c.label}と人、どちらにもやさしい時間を。</p><div><a href="#find">お店を探す</a><a href="#guide">運営ポリシー</a><a href="#journal">広告掲載について</a></div><small>© 2026 PET BIYORI. 店舗情報・口コミ傾向は公開情報を編集部が要約。写真はイメージです。</small></footer>
  {quiz&&<div className="modal-backdrop" onClick={()=>setQuiz(false)}><section className="modal" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setQuiz(false)}>×</button><p className="eyebrow">YOUR {mode.toUpperCase()} CAFE TYPE</p><h2>あなたには「{c.quiz}」</h2><p>{c.quizText}</p><button className="button primary" onClick={()=>{setQuiet(true);setQuiz(false);document.querySelector("#find")?.scrollIntoView({behavior:"smooth"})}}>おすすめを見る →</button></section></div>}
 </main>
}

export default function Home(){return <main className="portal"><div className="portal-intro"><p className="eyebrow">PET BIYORI</p><h1>どちらの気配に、<br/>会いにいきますか。</h1><p>犬のまっすぐさも、猫の静けさも知っている。<br/>ひとりの時間に寄り添う場所を、動物別にご案内します。</p></div><div className="portal-choices"><a className="portal-card cat-choice" href="/cat-cafe/"><span>CAT CAFE GUIDE</span><div><small>静かな気配に癒されたい日</small><h2>猫派ページへ</h2><b>→</b></div></a><a className="portal-card dog-choice" href="/dog-cafe/"><span>DOG CAFE GUIDE</span><div><small>まっすぐな笑顔に会いたい日</small><h2>犬派ページへ</h2><b>→</b></div></a></div></main>}
